// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROvkvnIHdLL7IjvdN3RsfNJV-sGbSEZU',
    appId: '1:66040998353:web:cc0ae9a86420d389fb98f0',
    messagingSenderId: '66040998353',
    projectId: 'cusecafeconnect-59117',
    authDomain: 'cusecafeconnect-59117.firebaseapp.com',
    storageBucket: 'cusecafeconnect-59117.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA49msLTbsJ5xnXoqmCy08h8XZLaE8PqCk',
    appId: '1:66040998353:android:30d07b7f6c6f9c13fb98f0',
    messagingSenderId: '66040998353',
    projectId: 'cusecafeconnect-59117',
    storageBucket: 'cusecafeconnect-59117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-eRBWzmB2s_GpApytXN0ibg83e8tp5CA',
    appId: '1:66040998353:ios:329c719b880fc147fb98f0',
    messagingSenderId: '66040998353',
    projectId: 'cusecafeconnect-59117',
    storageBucket: 'cusecafeconnect-59117.appspot.com',
    iosBundleId: 'com.example.cuseCafeConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-eRBWzmB2s_GpApytXN0ibg83e8tp5CA',
    appId: '1:66040998353:ios:329c719b880fc147fb98f0',
    messagingSenderId: '66040998353',
    projectId: 'cusecafeconnect-59117',
    storageBucket: 'cusecafeconnect-59117.appspot.com',
    iosBundleId: 'com.example.cuseCafeConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDROvkvnIHdLL7IjvdN3RsfNJV-sGbSEZU',
    appId: '1:66040998353:web:a30be7e2366238b7fb98f0',
    messagingSenderId: '66040998353',
    projectId: 'cusecafeconnect-59117',
    authDomain: 'cusecafeconnect-59117.firebaseapp.com',
    storageBucket: 'cusecafeconnect-59117.appspot.com',
  );
}
